<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <RootNamespace>Ink</RootNamespace>
    <AssemblyName>inklecate</AssemblyName>
  </PropertyGroup>

  <PropertyGroup>
    <Company>inkle Ltd</Company>
    <Authors>InkleStudios</Authors>
    <Copyright>inkle Ltd</Copyright>
    <RepositoryUrl>https://github.com/inkle/ink</RepositoryUrl>
    <PackageProjectUrl>https://github.com/inkle/ink</PackageProjectUrl>
    <PackageLicenseUrl>https://github.com/inkle/ink/blob/master/LICENSE.txt</PackageLicenseUrl>
    <RepositoryType>git</RepositoryType>
  </PropertyGroup>

  <!-- PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DebugType>none</DebugType>
    <DebugSymbols>false</DebugSymbols>
  </PropertyGroup -->

  <ItemGroup>
    <ProjectReference Include="..\compiler\ink_compiler.csproj" />
    <ProjectReference Include="..\ink-engine-runtime\ink-engine-runtime.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="OmniSharp.Extensions.LanguageServer" Version="0.14.2" />
    <PackageReference Include="Serilog.Extensions.Logging" Version="3.0.1" />
    <PackageReference Include="Serilog.Sinks.File" Version="4.1.0" />

    <!-- Avoid NU1605 -->
    <PackageReference Include="System.IO.FileSystem.Primitives" Version="4.3.0" />
    <PackageReference Include="System.Runtime.Handles" Version="4.3.0" />
    <PackageReference Include="System.Text.Encoding.Extensions" Version="4.3.0" />
    <!-- *************** -->
  </ItemGroup>

  <ItemGroup>
    <Folder Include="LanguageServerProtocol\Backend\" />
    <Folder Include="LanguageServerProtocol\Backend\Interfaces\" />
    <Folder Include="LanguageServerProtocol\Workspace\" />
    <Folder Include="LanguageServerProtocol\Workspace\Interfaces\" />
    <Folder Include="LanguageServerProtocol\Handlers\" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="LanguageServerProtocol\README.md" />
  </ItemGroup>

  <ItemGroup>
    <!-- this is planned for the future sdk versions
      <InternalsVisibleTo Include="ink-tests"/>
    -->
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">
      <_Parameter1>ink-tests</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>

</Project>